### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/codeforsanjose.github.io#13]
The page build completed successfully, but returned the following warning for the `master` branch:

Your site's DNS settings are using a custom subdomain, www.codeforsanjose.com, that's set up as an A record. 

We recommend you change this to a CNAME record pointing at codeforsanjose.github.io. 

For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

**Comment by bvi1994** [comment]
https://www.codeforsanjose.com/ works now. Checked via Slack.
