### ISSUE TITLE
Buttons in "Discuss, Connect, Create" are not uniform

### ISSUE THREAD

**Issue by bvi1994** [codeforsanjose/codeforsanjose.github.io#14]
The buttons at the bottom of each div are not evenly sized or space across each of the divs. Perhaps it's worth centering those bottons?

**Comment by biesnecker** [comment]
It appears that this is already complete? The buttons are not the same size, but they're lined up vertically and horizontally, and are centered in their respective divs? Can this be closed, or was there another change intended?
