### ISSUE TITLE
Events should contain Meetup Information on the site

### ISSUE THREAD

**Issue by bvi1994** [codeforsanjose/codeforsanjose.github.io#17]
Perhaps we can have the "Events" tab not redirect to the Meetup page. Maybe we can embed some of the information on Meetup using the Meetup API. 

https://www.meetup.com/meetup_api/

**Comment by sjconnor** [comment]
Would it solve the problem to just hit the Meetup API, display **upcoming events** and perhaps a few key bits of data (maybe the "what we're about" bit), and have a link to the Meetup page itself for individuals wanting more info than that?

If the above would meet the page's needs, this is in my wheelhouse and I could help.

**Comment by sjconnor** [comment]
Looks like there's an endpoint that would be perfect for this - just shows upcoming (not past) events - but could use it sans /events to get photos or other misc. data about meetup.

http://api.meetup.com/code-for-san-jose/events
