### ISSUE TITLE
/data section on site not found

### ISSUE THREAD

**Issue by akshat-harit** [codeforsanjose/codeforsanjose.github.io#2]
Visiting http://codeforsanjose.com/data/ returns web page with the following text

Cannot GET /data/

**Comment by EngineerEmily** [comment]
We are currently having issues with the website. Until then, we can link to this page for the data sources.
http://codeforsanjose.github.io/data

**Comment by ychoy** [comment]
Data should probably be added as a page under Docs. Or Included in the Navbar.

**Comment by ychoy** [comment]
Added Data under Docs: http://www.codeforsanjose.com/docs/data/
