### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/codeforsanjose.github.io#7]
Embed tweets from @codeforsanjose on homepage

**Comment by bvi1994** [comment]
Where do you think is the best place to embed those tweets?

**Comment by ychoy** [comment]
Perhaps a column next to Thanks to our Sponsors content. Thanks to our Sponsors would have 3/4 the screen, and the Twitter feed would have 1/4 of the screen. On mobile view, the Twitter feed would appear after the Thanks to our Sponsors content.
