### ISSUE TITLE
Events Page Still Has Placeholder Text

### ISSUE THREAD

**Issue by sunnymui** [codeforsanjose/codeforsanjose.github.io#71]
View [https://www.codeforsanjose.org/events](https://www.codeforsanjose.org/events)

The subtitle text and the body text for the first section titled "New to CFSJ" is generated placeholder text. 

Scroll down and the subtitle text right under "Frequently Asked Questions" also has placeholder text. FAQ answers are also placeholder text.

I'm assuming that should be actual content.

**Comment by ErikaVasNormandy** [comment]
Resolved this on Webflow's end
