### ISSUE TITLE
Contact Page Mailto Link Has Incorrect Email Address

### ISSUE THREAD

**Issue by sunnymui** [codeforsanjose/codeforsanjose.github.io#72]
The `mailto:` anchor has the incorrect email address. 

It currently points to: contact@jobboard.com

**Comment by ErikaVasNormandy** [comment]
Updated this on https://apply.codeforsanjose.org/contact along with removing placeholder text since this will be on https://codeforsanjose.org/faq.html

https://apply.codeforsanjose.org/contact now has this hotbutton fixed
